name: Pomodoro

packages:
  AppState:
    url: https://github.com/0xLeif/AppState.git
    exactVersion: 3.0.1
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    exactVersion: 1.19.3

options:
  bundleIdPrefix: com.0xleif
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"
  defaultConfig: Debug
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    OTHER_SWIFT_FLAGS: -enable-experimental-feature StrictConcurrency
    ENABLE_TESTABILITY: YES

targets:
  Pomodoro:
    type: application
    platform: [iOS, macOS]
    sources:
      - path: Sources
    dependencies:
      - package: AppState
        product: AppState
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.0xleif.AppStatePomodoro
        INFOPLIST_FILE: Sources/App/Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"

  PomodoroTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Pomodoro_iOS
      - package: SnapshotTesting
        product: SnapshotTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.0xleif.AppStatePomodoro.tests
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        GENERATE_INFOPLIST_FILE: YES

schemes:
  Pomodoro-iOS:
    build:
      targets:
        Pomodoro_iOS: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - PomodoroTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  Pomodoro-macOS:
    build:
      targets:
        Pomodoro_macOS: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
